FROM {ARG_FROM}

RUN set -ex \
    && apt-get update \
    && apt-get -y install protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex \
    && GO111MODULE=on \
    && GOPATH=/goprotogen \
    && go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
