#!/bin/sh

# Build a container to build a Go application inside of and
# optionally push it to a docker registry

set -eu

. scripts/environment

: "${BUILD_APPNAME:=${DEFAULT_BUILD_APPNAME}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"
: "${BASE_BUILD_IMAGE:=${DEFAULT_BUILD_IMAGE}}"

usage_and_exit() {
    >&2 echo "usage: $(basename "$0") [--push]"
    exit 1
}

PUSH=false
while [ $# -gt 0 ]; do
    key="$1"
    case $key in
        --push)
            PUSH=true
            shift # past argument
            ;;
        *)  # unknown option
            usage_and_exit
            ;;
    esac
done

# Prepare the Dockerfile
sed -e "s|{ARG_FROM}|$DEFAULT_BASE_BUILD_IMAGE|g" Dockerfile.build > .dockerfile.build

# Build the container image and tidy up
BUILD_IMAGE=${BASE_BUILD_IMAGE}
docker build -t ${BUILD_IMAGE} -f .dockerfile.build .
rm -f .dockerfile.build

# Push to registry if required
if [ ${PUSH} = true ]; then
  docker push ${BUILD_IMAGE}
fi

exit 0
