#!/bin/sh

# Containerise application
. scripts/environment
set -eu


: "${OS:=${DEFAULT_OS}}"
: "${ARCH:=${DEFAULT_ARCH}}"
: "${APPNAME:=${DEFAULT_APPNAME}}"
: "${VERSION:=${DEFAULT_VERSION}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"
: "${BASEIMAGE:=${DEFAULT_BASE_IMAGE}}"
: "${APPSOURCE:=${DEFAULT_APPSOURCE}}"
: "${APPCONFIG:=${DEFAULT_APPCONFIG}}"
: "${IMAGENAME:=${DEFAULT_IMAGENAME}}"

if [ "$ARCH" != "$DEFAULT_ARCH" ]; then
  APPSOURCE=bin/${OS}_${ARCH}
fi

echo "Containerising ${APPSOURCE}/${APPNAME} for ${ARCH}"
if [ -f ${APPSOURCE}/${APPNAME} ]; then
  TAG=${VERSION}__${OS}_${ARCH}
  sed -e "s|{ARG_SRC}|${APPSOURCE}|g" \
      -e "s|{ARG_BIN}|${APPNAME}|g" \
      -e "s|{ARG_FROM}|${BASEIMAGE}|g" \
      -e "s|{ARG_CFG}|${APPCONFIG}|g" \
    Dockerfile.in > dockerfile-${APPNAME}-${OS}_${ARCH}
  docker build -t ${IMAGENAME}:${TAG} -f dockerfile-${APPNAME}-${OS}_${ARCH} .
  rm -f dockerfile-${APPNAME}-${OS}_${ARCH}
else
  echo "Could not find ${APPSOURCE}/${APPNAME}"
  exit 1
fi
