#!/bin/sh

# Build a Go application

set -eu

. scripts/environment
. ./version

: "${OS:=${DEFAULT_OS}}"
: "${ARCH:=${DEFAULT_ARCH}}"
: "${APPNAME:=${DEFAULT_APPNAME}}"
: "${VERSION:=${DEFAULT_VERSION}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"
: "${BUILD_IMAGE:=${DEFAULT_BUILD_IMAGE}}"
: "${PROTODIR:=${DEFAULT_PROTODIR}}"
: "${http_proxy:=}"
: "${https_proxy:=}"
: "${no_proxy:=}"

# If running in a terminal, pass --tty to docker i.e. allocate a pseudo-tty for the container
[ -t 1 ] && TTY="--tty" || TTY=""

usage_and_exit() {
    >&2 echo "usage: $(basename "$0") [--push]"
    exit 1
}

PUSH=false
while [ $# -gt 0 ]; do
    key="$1"
    case $key in
        --push)
            PUSH=true
            shift # past argument
            ;;
        *)  # unknown option
            usage_and_exit
            ;;
    esac
done

# Build the Go application
echo "Building ${APPNAME} for ${ARCH}"
docker run --rm \
  ${TTY} \
  -v $(pwd):/src -w /src \
  -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e no_proxy=$no_proxy \
  -e ARCH=${ARCH} \
  -e APPNAME=${APPNAME} \
  -e VERSION=${VERSION} \
  -e PROTODIR=${PROTODIR} \
  ${BUILD_IMAGE} \
  build/build.sh

exit 0
