#!/bin/sh

# Package application for Predix Edge OS

set -eu

DEFAULT_OS=linux
DEFAULT_ARCH=amd64
DEFAULT_APPNAME=diffie-hellman-service
DEFAULT_VERSION=1.0.0
DEFAULT_REGISTRY=registry.gear.ge.com/csp

: "${OS:=${DEFAULT_OS}}"
: "${ARCH:=${DEFAULT_ARCH}}"
: "${APPNAME:=${DEFAULT_APPNAME}}"
: "${VERSION:=${DEFAULT_VERSION}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"

# Generate docker-compose.yml
COMPOSE_TEMPLATE=docker-compose-template.yml
sed -e "s|{ARG_OS}|${OS}|g" \
    -e "s|{ARG_ARCH}|${ARCH}|g" \
    -e "s|{ARG_NAME}|${APPNAME}|g" \
    -e "s|{ARG_VERSION}|${VERSION}|g" \
    ${COMPOSE_TEMPLATE} > docker-compose.yml

# Generate manifest.json
MANIFEST_TEMPLATE=manifest-template.json
sed -e "s|{ARG_OS}|${OS}|g" \
    -e "s|{ARG_ARCH}|${ARCH}|g" \
    -e "s|{ARG_NAME}|${APPNAME}|g" \
    -e "s|{ARG_VERSION}|${VERSION}|g" \
    ${MANIFEST_TEMPLATE} > manifest.json

# Convert container
echo "Packaging ${APPNAME} for ${ARCH}"
TARBALLNAME=${APPNAME}-${VERSION}-${ARCH}.tar
CONTAINERNAME=${REGISTRY}/$APPNAME:${VERSION}__${OS}_${ARCH}
docker save -o $TARBALLNAME $CONTAINERNAME
tar -czf ${TARBALLNAME}.gz ${TARBALLNAME} docker-compose.yml manifest.json

# Tidy up
rm -f $TARBALLNAME
rm -f manifest.json
rm -f docker-compose.yml

exit 0
