#!/bin/sh

# Push a Go application container

set -eu

DEFAULT_OS=linux
DEFAULT_ARCH=amd64
DEFAULT_APPNAME=diffie-hellman-service
DEFAULT_VERSION=1.0.0
DEFAULT_REGISTRY=registry.gear.ge.com/csp

: "${OS:=${DEFAULT_OS}}"
: "${ARCH:=${DEFAULT_ARCH}}"
: "${APPNAME:=${DEFAULT_APPNAME}}"
: "${VERSION:=${DEFAULT_VERSION}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"

TAG=${VERSION}__${OS}_${ARCH}

# Push to registry if required
echo "Pushing ${REGISTRY}/${APPNAME}:${TAG}"
docker push ${REGISTRY}/${APPNAME}:${TAG}

exit 0
