#!/bin/sh

# Test a Go application

set -eu

DEFAULT_OS=linux
DEFAULT_ARCH=amd64
DEFAULT_APPNAME=diffie-hellman-service
DEFAULT_VERSION=1.0.0
DEFAULT_REGISTRY=registry.gear.ge.com/csp
DEFAULT_BUILD_IMAGE=diffie-hellman-service-golang:1.16.0-buster

: "${OS:=${DEFAULT_OS}}"
: "${ARCH:=${DEFAULT_ARCH}}"
: "${APPNAME:=${DEFAULT_APPNAME}}"
: "${VERSION:=${DEFAULT_VERSION}}"
: "${REGISTRY:=${DEFAULT_REGISTRY}}"
: "${BUILD_IMAGE:=${DEFAULT_BUILD_IMAGE}}"
: "${http_proxy:=}"
: "${https_proxy:=}"
: "${no_proxy:=}"

# If running in a terminal, pass --tty to docker i.e. allocate a pseudo-tty for the container
[ -t 1 ] && TTY="--tty" || TTY=""

# Test the application
docker run \
  ${TTY} \
  -v $(pwd):/src -w /src \
  -e http_proxy=$http_proxy -e https_proxy=$http_proxy -e no_proxy=$no_proxy \
  ${REGISTRY}/${BUILD_IMAGE} build/test.sh cmd pkg

exit 0
